const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{for(const locale of ['', 'en/']){const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto('http://127.0.0.1:8765/'+locale);
await page.locator('#btnTerms').click();const text=await page.locator('.terms-fork').innerText();if(!locale)assert.ok(text.includes('このfork版は、ワンストップで動画作成が完成する事を目指して\nオリジナル版JIZURAに機能を追加したものです。\n編集・書き出しはブラウザ内で処理します。'));assert.equal(await page.locator('.terms-fork a').getAttribute('href'),'https://github.com/hirazisora/JIZURA');await page.locator('#termsDlg button').click();
await page.locator('#projectMenu summary').click();assert.equal(await page.locator('#btnNew').isVisible(),true);await page.locator('#outputMenu summary').click();assert.equal(await page.locator('#btnNew').isVisible(),false);assert.equal(await page.locator('#btnAE').isVisible(),true);
await page.evaluate(()=>{J.ui.project.videoSize={w:64,h:64};J.ui.project.durationOverride=.15;J.ui.project.lyrics='A';J.uiApi.syncUI();J.uiApi.replan();window.exportCalls=[];for(const key of ['exportMP4','exportPNGZip']){const original=J[key];J[key]=async opts=>{window.exportCalls.push({key,transparent:opts.transparent,quality:opts.quality,size:J.outputSize(opts.project)});return original(opts)}}});
for(const [menu,button,extension,kind] of [['menuMP4','btnMP4',/\.mp4$/,'mp4'],['menuPNG','btnPNG',/_png\.zip$/,'png'],['menuPNGA','btnPNGA',/_alpha_png\.zip$/,'pnga']]){
 if(!(await page.locator('#outputMenu').evaluate(el=>el.open)))await page.locator('#outputMenu summary').click();await page.locator('#'+menu).click();assert.equal(await page.locator('#exportDlg').isVisible(),true);assert.equal(await page.locator('#outAspect').count(),1);assert.equal(await page.locator('#outQuality').isVisible(),kind==='mp4');assert.equal(await page.locator('#outAudio').isVisible(),kind==='mp4');assert.equal(await page.locator('#outKey').isVisible(),kind!=='pnga');
 if(kind==='mp4'){await page.locator('#outQuality').selectOption('standard');await page.locator('#outFps').selectOption('30')}
 await page.screenshot({path:'../export-'+kind+'-'+(locale?'en':'ja')+'.png'});
 const done=page.waitForEvent('download');await page.locator('#'+button).click();const download=await done;assert.match(download.suggestedFilename(),extension);const parts=[];for await(const b of await download.createReadStream())parts.push(b);assert.ok(Buffer.concat(parts).length>100);
 await page.waitForFunction(()=>!J.ui.exporting);await page.locator('#btnCloseExport').click();await page.waitForFunction(()=>document.querySelector('#exportSettings').parentElement.id==='exportSettingsHome');assert.equal(await page.locator('#outFps').inputValue(),'30');
}
const calls=await page.evaluate(()=>window.exportCalls);assert.equal(calls[0].quality,'standard');assert.deepEqual(calls.map(c=>c.size),[[64,64],[64,64],[64,64]]);assert.equal(calls[1].transparent,false);assert.equal(calls[2].transparent,true);
await page.locator('#modePro').click();await page.locator('[data-tab="out"]').click();assert.equal(await page.locator('#outQuality').isVisible(),true);assert.equal(await page.locator('#btnPNG').isVisible(),true);
await page.locator('#outputMenu summary').click();await page.locator('#menuPNG').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#exportDlg').open&&document.querySelector('#exportSettings').parentElement.id==='exportSettingsHome');assert.equal(await page.locator('#btnMP4').isVisible(),true);
assert.deepEqual(errors,[]);console.log(locale||'ja','menus, modal reuse, settings sync, actual MP4/PNG/alpha ZIP export: OK');await page.close();}
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
