const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');

const context = vm.createContext({ window: {} });
vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'src', '01_util.js'), 'utf8'), context);
for (const key of ['LAYOUT_ORDER', 'ENTER_ORDER', 'EXIT_ORDER', 'HOLD_ORDER', 'DECOR_ORDER']) context.window.J[key] = [];
vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'src', '08_planner.js'), 'utf8'), context);
const J = context.window.J;
const mixed = J.parseLyrics('[00:02]First\nInserted\n[00:05]Last').lines;
assert.deepEqual(Array.from(mixed, line => line.text), ['First', 'Inserted', 'Last'], 'mixed LRC and plain lyrics keep the written order');
const timed = J.parseLyrics('[00:05]Last\n[00:02]First').lines;
assert.deepEqual(Array.from(timed, line => line.text), ['First', 'Last'], 'fully timed LRC lyrics still sort by timestamp');
assert.deepEqual(Array.from(J.parseLyrics('\\#literal\n\\[00:02]literal').lines, line => line.text), ['#literal', '[00:02]literal']);
const grouped = J.parseLyrics('{\n[00:01]First\n# ignored\n[00:02]Second\n}\n[00:03]Outside\n{[00:04]Third\n[00:05]Fourth}').lines;
assert.deepEqual(Array.from(grouped, line => line.group), [0, 0, null, 1, 1]);
assert.deepEqual(Array.from(grouped, line => line.text), ['First', 'Second', 'Outside', 'Third', 'Fourth']);
assert.equal(J.parseLyrics(String.raw`First\nSecond`).lines[0].text, 'First\nSecond');
assert.equal(J.parseLyrics(String.raw`First\\nSecond`).lines[0].text, String.raw`First\nSecond`);
const escaped = J.parseLyrics(String.raw`\{\*literal\* \~quiet\~ \/ \} \\`).lines[0];
assert.equal(escaped.text, '{*literal* ~quiet~ / } \\');
assert.equal(escaped.group, null);
assert.equal(escaped.emph.length + escaped.soft.length, 0);
const strength = J.parseLyrics(String.raw`plain *BIG/LOUD* ~small\nquiet~`).lines[0];
assert.equal(strength.text, 'plain BIG LOUD small\nquiet');
assert.deepEqual(Array.from(strength.strengthSpans, x => ({...x})), [{ start: 5, end: 12, strong: true }, { start: 12, end: 22, strong: false }]);
assert.equal(J.parseLyrics('{\nOpen group').lines[0].group, 0, 'an unfinished group remains usable while typing');
console.log('Lyric parsing tests passed');
