const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = vm.createContext({ window: {} });
for (const file of ['01_util.js', '08d_media.js']) vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'src', file), 'utf8'), context);
const J = context.window.J;
const items = ['a', 'b', 'c'].map(id => ({ id, name: id + '.png', type: 'image' }));
const project = { seed: 42, media: { items, randomOrder: true, seed: 4, timing: { lineTimes: { 1: 3 } }, overrides: { a: { layout: 'contain' } }, blend: 'screen', opacity: 40 } };
const lyric = { duration: 9, lines: [{ start: 0.4 }, { start: 2 }, { start: 5 }] };
const a = J.planMedia(project, lyric);
const b = J.planMedia(project, lyric);
assert.equal(JSON.stringify(a), JSON.stringify(b), 'random order must be deterministic');
assert.deepEqual(Array.from(a.cuts.map(c => c.start)), [0.4, 3, 5]);
assert.equal(a.cuts[2].end, 9);
assert.equal(a.blend, 'screen');
assert.equal(a.opacity, 40);
assert.equal(J.mediaAt({ media: a }, 3.2).index, 1);
assert.equal(items.length, 3, 'planning must not mutate uploaded order');
const solo = J.planMedia({ seed: 1, media: { items: [{ id: 'v', name: 'v.webm', type: 'video', duration: 7 }] } }, { duration: 3, lines: [] });
assert.equal(solo.duration, 7);
assert.equal(solo.cuts.length, 1);
console.log('Media planning tests passed');
