const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = vm.createContext({ window: {} });
for (const file of ['01_util.js', '08d_media.js']) vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'src', file), 'utf8'), context);
const J = context.window.J;
const items = ['a', 'b', 'c'].map(id => ({ id, name: id + '.png', type: 'image' }));
const project = { seed: 42, media: { items, randomOrder: true, seed: 4, timing: { lineTimes: { 1: 3 } }, overrides: { a: { layout: 'contain' } }, blend: 'screen', opacity: 40 } };
const lyric = { duration: 9, lines: [{ start: 0.4 }, { start: 2 }, { start: 5 }] };
const a = J.planMedia(project, lyric);
const b = J.planMedia(project, lyric);
assert.equal(JSON.stringify(a), JSON.stringify(b), 'random order must be deterministic');
assert.deepEqual(Array.from(a.cuts.map(c => c.start)), [0.4, 3, 5]);
assert.equal(a.cuts[2].end, 9);
assert.equal(a.blend, 'screen');
assert.equal(a.opacity, 40);
assert.equal(J.mediaAt({ media: a }, 3.2).index, 1);
assert.equal(items.length, 3, 'planning must not mutate uploaded order');
const solo = J.planMedia({ seed: 1, media: { items: [{ id: 'v', name: 'v.webm', type: 'video', duration: 7 }] } }, { duration: 3, lines: [] });
assert.equal(solo.duration, 7);
assert.equal(solo.cuts.length, 1);
const loop = J.planMedia({ seed: 1, media: { items: items.slice(0, 2), loop: true, cutCount: 5, cutOverrides: { 0: { layout: 'cover' }, 2: { layout: 'contain' } } } }, { duration: 8, lines: [] });
assert.deepEqual(Array.from(loop.cuts.map(c => c.itemId)), ['a', 'b', 'a', 'b', 'a']);
assert.equal(loop.cuts[2].layout, 'contain');
assert.equal(loop.cuts[0].layout === 'contain', false, 'repeated cuts can have independent settings');
assert.equal(loop.duration, 20, 'media-only duration includes repeated cuts');
assert.equal(J.mediaAt({ media: loop }, loop.cuts[4].start + 0.1).itemId, 'a');
const noLoop = J.planMedia({ seed: 1, media: { items: items.slice(0, 2), loop: false, cutCount: 5 } }, { duration: 8, lines: [] });
assert.equal(noLoop.cuts.length, 2);
const shuffled = J.planMedia({ seed: 42, media: { items, loop: true, cutCount: 8, randomOrder: true } }, { duration: 10, lines: [] });
assert.deepEqual(Array.from(shuffled.cuts.slice(0, 3).map(c => c.itemId)), Array.from(shuffled.cuts.slice(3, 6).map(c => c.itemId)));
console.log('Media planning tests passed');
